name: Bash CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make test executable
        run: chmod +x bash-test/test_backup.sh

      - name: Run Bash tests
        run: ./bash-test/test_backup.sh